//
//  Supported Curriculums.swift
//  AppBookDataAnalyzer
//
//  Created by Jeremy Kelleher on 2/23/22.
//

import Foundation

extension Curriculum {
    
    /// A representation of the INSITE curriculum used in the 2022-04-18 research study
    static let insite20220418 = Curriculum(
        appbooks: [
            AppBook(id: 97, title: "Intro", pageCount: 22),
            AppBook(id: 26, title: "Values", pageCount: 19),
            AppBook(id: 31, title: "GoalSetting", pageCount: 16),
            AppBook(id: 94, title: "DecisionMaking", pageCount: 19),
            AppBook(id: 30, title: "Education", pageCount: 10),
            AppBook(id: 41, title: "Budgeting", pageCount: 14),
            AppBook(id: 77, title: "ExploringCareers", pageCount: 32),
            AppBook(id: 82, title: "WaysToWork", pageCount: 20),
            AppBook(id: 80, title: "GetAJob", pageCount: 23),
            AppBook(id: 81, title: "Business", pageCount: 13),
            AppBook(id: 90, title: "Disclosure", pageCount: 19),
            AppBook(id: 91, title: "SoftSkills", pageCount: 22),
            AppBook(id: 92, title: "MockInterview", pageCount: 12),
            AppBook(id: 95, title: "SelfAdvocacy", pageCount: 21),
            AppBook(id: 96, title: "STEM", pageCount: 10),
        ],
        jobs: [
            Job(id: 1, title: "Registered Nurse"),
            Job(id: 2, title: "Veterinarian Technician"),
            Job(id: 3, title: "X-Ray Technician"),
            Job(id: 4,  title: "EMT and Paramedic"),
            Job(id: 5,  title: "Lab Technician"),
            Job(id: 6,  title: "Physical Therapist"),
            Job(id: 7,  title: "Carpenter"),
            Job(id: 8,  title: "Plumber"),
            Job(id: 9,  title: "Architect"),
            Job(id: 10,  title: "Electrician"),
            Job(id: 11,  title: "Civil Engineer"),
            Job(id: 12,  title: "Welder"),
            Job(id: 13,  title: "Solar Technician"),
            Job(id: 14,  title: "Wind Turbine Technician"),
            Job(id: 15,  title: "Park Ranger"),
            Job(id: 16,  title: "Marine Biologist"),
            Job(id: 17,  title: "Commercial Diver"),
            Job(id: 18,  title: "Landscape Architect"),
            Job(id: 19,  title: "Computer Programmer"),
            Job(id: 20,  title: "Video Game Developer"),
            Job(id: 21,  title: "Cyber Security Analyst"),
            Job(id: 22,  title: "Web Developer"),
            Job(id: 23,  title: "CAD Drafter"),
            Job(id: 24,  title: "Computer Support Specialist"),
            Job(id: 25,  title: "Auto Body & Paint Tech"),
            Job(id: 26,  title: "Auto Mechanic"),
            Job(id: 27,  title: "Auto Tire Technician"),
            Job(id: 28,  title: "Delivery Driver"),
            Job(id: 29,  title: "Brick Mason"),
            Job(id: 30,  title: "Carpenter Helper"),
            Job(id: 31,  title: "Civil Engineer Tech"),
            Job(id: 32,  title: "Construction Laborer"),
            Job(id: 33,  title: "Construction Manager"),
            Job(id: 34,  title: "HVAC Tech"),
            Job(id: 35,  title: "Maintenance / Repair Worker"),
            Job(id: 36,  title: "Painter (Construction)"),
            Job(id: 37,  title: "Baker"),
            Job(id: 38,  title: "Bartender"),
            Job(id: 39,  title: "Chef / Head Cook"),
            Job(id: 40,  title: "Cook"),
            Job(id: 41,  title: "Dishwasher"),
            Job(id: 42,  title: "Food Preparation"),
            Job(id: 43,  title: "Host / Hostess"),
            Job(id: 44,  title: "Hotel Desk Clerk"),
            Job(id: 45,  title: "Housekeeper"),
            Job(id: 46,  title: "Janitor"),
            Job(id: 47,  title: "Waiter / Waitress"),
            Job(id: 48,  title: "Barber"),
            Job(id: 49,  title: "Hairstylist"),
            Job(id: 50,  title: "Massage Therapist"),
            Job(id: 51,  title: "Nail Sylist"),
            Job(id: 52,  title: "Skin Care Specialist"),
            Job(id: 53,  title: "Tailor / Sewer"),
            Job(id: 54,  title: "Dental Hygienist"),
            Job(id: 55,  title: "Home Health Aide"),
            Job(id: 56,  title: "Hospital Cafeteria Cook"),
            Job(id: 57,  title: "Nursing Assistant"),
            Job(id: 58,  title: "Machinist"),
            Job(id: 59,  title: "Packaging Worker"),
            Job(id: 60,  title: "Production Worker"),
            Job(id: 61,  title: "Sheet Metal Worker"),
            Job(id: 62,  title: "Audio / Visual Technician"),
            Job(id: 63,  title: "Film and Video Editor"),
            Job(id: 64,  title: "Graphic Designer"),
            Job(id: 65,  title: "Photographer"),
            Job(id: 66,  title: "Reporter Print and TV"),
            Job(id: 67,  title: "Telecommunications Installer"),
            Job(id: 68,  title: "Cashier"),
            Job(id: 69,  title: "Customer Service Rep"),
            Job(id: 70,  title: "Shipping / Stocking Clerk"),
        ],
        analytics: [
            TimeOnPage(),
            TableOfContentsOpened(),
            MultipleChoiceAttempts(),
            MultipleChoiceTapCount(),
            QuestionFeedbackModalOpened(),
            SwipeableRoundOneLeft(),
            SwipeableRoundOneRight(),
            SwipeableChanges(),
            SketchPadDrawStrokeCount(),
            SketchPadImageCount(),
            OpenResponseAttempts(),
            OpenResponseCharacterCount(),
            OpenResponseContainsEmoji(),
            PathBuilderNotebookItemsCount(),
            PathBuilderTextItemsCount(),
            PathBuilderLinksCreated(),
            MovieCreatorTextItemCount(),
            MovieCreatorSketchItemCount(),
            MovieCreatorPathBuilderItemCount(),
            MovieCreatorNotebookItemCount(),
            MovieCreatorThemeChangeCount(),
            MovieCreatorNarrationChangeCount(),
            MovieCreatorAddSlideCount(),
            JobExploreCount(),
            JobMainImageViews(),
            JobFavoritedCount(),
            JobUnfavoritedCount(),
            MoviePlayTime(),
        ]
    )
    
}
